### PR TITLE
refactor(game): be more precise, and correct cost

### PR DESCRIPTION
**Pull request by balthazar**
It seems pretty difficult to get an extra point, so this is most likely a typo.

### CODE REVIEW

**Comment by balthazar** [comment]
## Why is this not a thing?

 I've followed the contributing guidelines at the :email: :
- the build is passing,
- no code coverage drop,
- my commit suits the [conventions](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md)
- can be automatically merged

Please show a little more interest with your contributors.

**Comment by meriadec** [comment]
It's not a thing, sorry.

**Comment by balthazar** [comment]
Can I have at least the invalid label?

**Comment by balthazar** [comment]
Well that's something

**Comment by meriadec** [comment]
It's fucking not.

**Pull request closed without merging**
